apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: emojivoto
spec:
  type: NodePort
  selector:
    app: web-svc
  ports:
  - name: http
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 8080
